version: 2
sources:
  - name: property_data
    database: practice-project-461104
    schema: property_data
    tables:
      - name: property_maintenance
        columns:
          - name: property_id
            tests:
              - not_null